on: 
  issues:
    types: [opened]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
    - uses: peter-evans/create-or-update-comment@v1
    - name: Create comment
        with:
          issue-number: 1
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'