on: 
  issues:
    types: [opened, reopened]

jobs:
  legal_teammates:
    runs-on: ubuntu-latest
    name: testing
    steps:
    - name: Finding Teammates
      id: legal-teammates
      uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        list-branch: "khaes-kth-registered_ids"
        list-file: "Registered_KTH_IDs.txt"
        main-branch: "2021"