on: 
  issues:
    types: [opened, reopened]

jobs:
  legal_teammates:
    runs-on: ubuntu-latest
    name: Legal Teammates
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Finding Teammates
      id: legal-teammates
      uses: Agriad/legal-teammates@v1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        list-branch: "demo"
        list-file: "Registered_IDs.txt"
        main-branch: "demo"